<?php
/**
 * Created by PhpStorm.
 * User: liyifei
 * Date: 2019/4/14
 * Time: 下午11:30
 */

namespace frontend\controllers;


use liyifei\base\controllers\ViewController;
use yii\web\Controller;

class MatchController extends Controller
{
    public $layout = '@frontend/views/layouts/main_w.php';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->enableCsrfValidation  = false;
    }

    public function actions()
    {
        $request = \Yii::$app->request;

        return [
            'update_match' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'update_match',
            ],
            'add_knock_player' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'add_knock_player',
            ],
            'update_knock_players' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'update_knock_players',
            ],
            'get_knockout_status' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_knockout_status',
            ],
            'get_knockout_players_in_match' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_knockout_players_in_match',
            ],
            'get_suggestion_from_subject' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_suggestion_from_subject',
            ],
            'get_subject_by_user_ware_id' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_subject_by_user_ware_id',
            ],
            'generate_subjects_to_knockout' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'generate_subjects_to_knockout',
            ],
            'get_subjects' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_subjects',
            ],
            'play_voice' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'play_voice',
            ],
            'battle_for_u3d' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'battle_for_u3d',
            ],
            'get_doc_subj' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_doc_subj',
            ],
            'get_doc' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_doc',
            ],
            'get_doc_score' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_doc_score',
            ],

            'get_story_match' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_story_match',
            ],
            'get_story_match_players_prop' => [
                'class' => 'frontend\actions\match\MatchApi',
                'action' => 'get_story_match_players_prop',
            ],

        ];
    }
}