<?php
/**
 * Created by PhpStorm.
 * User: liyifei
 * Date: 2019/4/14
 * Time: 下午11:30
 */

namespace frontend\controllers;


use liyifei\base\controllers\ViewController;
use yii\web\Controller;

class UploadController extends Controller
{
    public $layout = '@frontend/views/layouts/main_n.php';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->enableCsrfValidation  = false;
    }

    public function actions()
    {
        return [
            'avatar' => [
                'class' => 'frontend\actions\upload\Index',
                'dirPrefix' => 'avatar',
            ],
//            'template' => [
//                'class' => 'frontend\actions\upload\Index',
//                'dirPrefix' => 'template',
//            ],
//            'index' => [
//                'class' => 'frontend\actions\upload\Index',
//                'dirPrefix' => 'files',
//            ],
        ];
    }
}